const forestParkMarathon = {
    id: 'fp-marathon',
    name: 'Forest Park Marathon',
    description: 'This route will take you across 2/3 of the length of Forest Park, through some of the less busy areas, and along some of the most scenic parts of Wildwood Trail. Note that this route is not a loop! It begins with a climb from the Lower Saltzman Road trailhead and ends at Lower Macleay Park.',
    distance: '26.38',
    elevation: '3200',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/lowerpark/dogwood2.jpg',
    imageOne: 'assets/images/lowerpark/lowermacleay/LM1.jpg',
    imageTwo: 'assets/images/lowerpark/WildCherryDogwood.jpg',
    imageThree: 'assets/images/lowerpark/lowermacleay/LowerMcleayTrailPic2.jpg',
    imageFour: 'assets/images/lowerpark/firelane1.jpg',
    thumbnailMap: 'assets/working/FP-MarathonTwo.svg',
    largeMap: 'assets/working/FP-MarathonTwo.svg',
    extraInfo: 'Access the starting trailhead on Lower Saltzman Road off of Highway 30. Limited street parking is available. The route ends at Lower Macleay Park, which has restrooms, parking, and a water fountain.',
    bathroom: true,
    familyFriendly: false,
    gpsCoordinates: '519280E 504589N',
    elevationChart: 'assets/lieferikson-firelane/elevation-lieferikson-firelane.svg'
};

const ramblers = {
    id: 'ramblers',
    name: 'Half Marathon +',
    description: 'This route is a half marathon plus some bonus mileage. It starts and ends at Lower Macleay Park (bathrooms!) and features a nice climb about halfway through when you reach Firelane 1. Roll into the finish with a nice descent over the last 3.5 miles.',
    distance: '14.03',
    elevation: '1600',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/lowerpark/sectionA.jpg',
    imageOne: 'assets/images/midpark/mid1.jpg',
    imageTwo: 'assets/images/midpark/wildwood.jpg',
    imageThree: 'assets/images/lowerpark/WildwoodTrailPic1.jpg',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/working/Ramblers.svg',
    largeMap: 'assets/working/Ramblers.svg',
    extraInfo: 'There is a small parking lot and ample street parking at the trailhead, which also features restrooms, a water fountain, and a picnic shelter. After you finish your run, you\'re close enough to the cafes and restaurants on NW 23rd to treat yourself to a post-run beer!',
    bathroom: true,
    familyFriendly: false,
    gpsCoordinates: '521529E 5042950N',
    elevationChart: './assets/creed.jpg'
};

const half = {
    id: 'half',
    name: 'Stumptown Races Half Marathon',
    description: 'This is the route for Go Beyond Racing\'s Stumptown Half Marathon race, which takes place in Forest Park every Memorial Day weekend. This course was developed by runners who have spent may hours finding the prettiest trails in the park, and features plenty of climb to make your legs and lungs burn.',
    distance: '13.1',
    elevation: '2000',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/lowerpark/wildcherry1.jpg',
    imageOne: 'assets/images/lowerpark/dogwood1.jpg',
    imageTwo: 'assets/images/lowerpark/WildCherryDogwood.jpg',
    imageThree: 'assets/images/lowerpark/holman.jpg',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/working/half.svg',
    largeMap: 'assets/working/half.svg',
    extraInfo: 'This course starts and ends at the intersection of Leif Erickson and Wild Cherry. To get there, take NW Thurman Rd until it ends at the Leif Erickson trailhead, where there is a small parking lot and ample street parking. Walk approximately a quarter mile to Wild Cherry. At the start of this route there are porto-potties.',
    bathroom: true,
    familyFriendly: false,
    gpsCoordinates: '45.540874, -122.726184',
    elevationChart: 'assets/elevation-profile/stumptown-half.png'
};

const ultra = {
    id: 'ultra',
    name: 'Stumptown Races 50k',
    description: 'This is the route for Go Beyond Racing\'s Stumptown 50K, the only ultramarathon trail race held within Portland city limits. This beautiful, challenging course is best tackled with a well-stocked hydration vest and a friend or six.',
    distance: '31',
    elevation: '4000',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/northpark/bluediamond.png',
    imageOne: 'assets/images/northpark/northwildwood.jpg',
    imageTwo: 'assets/images/midpark/mid5.jpg',
    imageThree: 'assets/images/northpark/bluediamond.png',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/working/ultra-map.svg',
    largeMap: 'assets/working/ultra-map.svg',
    extraInfo: 'This course starts and ends at the intersection of Leif Erickson and Wild Cherry. To get there, take NW Thurman Rd until it ends at the Leif Erickson trailhead, where there is a small parking lot and ample street parking. Walk approximately a quarter mile to Wild Cherry. The course begins with a small out and back heading back down Leif Erickson toward Thurman, which is designed to allow runners to spread out. While this course does include a bathroom, it is at the start and end of the route, so plan accordingly.',
    bathroom: true,
    familyFriendly: false,
    gpsCoordinates: '45.540874, -122.726184',
    elevationChart: 'assets/elevation-profile/elevation50k.png'
};

const springville = {
    id: 'springville',
    name: 'Springville Baptism',
    description: 'Situated in the middle-north section of the park, this route will provide spectacular views without a lot of crowds, even on nice weekend days. Springville Baptism starts with a climb up to spectacular views, and then a tour through some of the lesser-used parts of the trail system.',
    distance: '5.5',
    elevation: '1566',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/midpark/maple.jpg',
    imageOne: 'assets/images/midpark/maple.jpg',
    imageTwo: 'assets/images/midpark/mid1.jpg',
    imageThree: 'assets/images/lowerpark/dogwood2.jpg',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/Springville-Baptism.svg',
    largeMap: 'assets/Springville-Baptism.svg',
    extraInfo: 'This routes starts and ends at Springville Road. It follows Firelane 7 and Leif Erikson to make a loop around a portion of Wildwood trail. There are no bathrooms near this route, so use a leaf!',
    bathroom: false,
    familyFriendly: false,
    gpsCoordinates: '45.540874, -122.726184',
    elevationChart: 'assets/elevation-profile/stumptown-half.png'
};

const saltzman = {
    id: 'saltzman',
    name: 'Saltzman Slog',
    description: 'This point-to-point run begins at the intersection of Firelane 5 and Leif Erikson and ends at the intersection of Saltzman Road trailhead and Leif Erikson.',
    distance: '5.3',
    elevation: '658',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/lowerpark/dogwood.jpg',
    imageOne: 'assets/images/lowerpark/leif1.jpg',
    imageTwo: 'assets/images/lowerpark/leif.jpg',
    imageThree: 'assets/images/lowerpark/holman.jpg',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/working/saltzman-slog-map.svg',
    largeMap: 'assets/working/saltzman-slog-map.svg',
    extraInfo: 'There are port-a-potties at the start of this route near Wildwood mile marker 11. The trailhead where this run starts has off-street parking, and there is street parking at the ending point.',
    bathroom: true,
    familyFriendly: false,
    gpsCoordinates: '45.540874, -122.726184',
    elevationChart: 'assets/elevation-profile/stumptown-half.png'
};

const trilliumtrek = {
    id: 'trillium',
    name: 'Trillium Trek',
    description: 'This route features diverse botany- look for the array of mushroom varieties near where Wildwood and Hardesty Trails intersect, and visit in the spring to see the trillium bloom!',
    distance: '4.75',
    elevation: '600',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/midpark/mid3.jpg',
    imageOne: 'assets/images/midpark/trillium.jpg',
    imageTwo: 'assets/images/midpark/maple.jpg',
    imageThree: 'assets/images/lowerpark/lowermacleay/LM6.jpg',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/working/Trillium-Trek.svg',
    largeMap: 'assets/working/Trillium-Trek.svg',
    extraInfo: 'This route is generally one of the flatter ones in the park, but use caution when descending Trillium Trail in the first half mile- it\'s steep, winding, and full of mud and tree roots! Parking is available along the road at the trailhead. This access point is popular with equestrians because the road is accessible to horse trailers.',
    bathroom: false,
    familyFriendly: true,
    gpsCoordinates: '45.540874, -122.726184',
    elevationChart: 'assets/elevation-profile/stumptown-half.png'
};

const pittock = {
    id: 'pittock',
    name: 'Pittock-It-Out',
    description: 'Make your way up to one of the best viewpoints in Portland by way of some of the most serene trails in any major city. Be prepared for a serious climb as you pass the Audubon Society and make your way up Wildwood Trail to Pittock Mansion. This route features three places to go to the bathroom, making it an excellent choice for after your morning coffee.',
    distance: '4.4',
    elevation: '1275',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/lowerpark/lowermacleay/LM1.jpg',
    imageOne: 'assets/images/lowerpark/UpperMcleayTrailPic1.jpg',
    imageTwo: 'assets/images/lowerpark/WildwoodTrailMeetsUpperMacleayTrail.jpeg',
    imageThree: 'assets/images/lowerpark/holman.jpg',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/working/Pittock-It-Out.svg',
    largeMap: 'assets/working/Pittock-It-Out.svg',
    extraInfo: 'Parking is usually readily available at the Leif Erikson trailhead where this route starts, and a quarter mile in you\'ll encounter your first bank of porto-potties. A few miles later, where Wildwood Trail crosses NW Cornell Blvd, you\'ll find the second potty pit stop. There\'s a large parking lot, bathrooms, water fountains, and even a gift shop when you finish at Pittock Mansion. This route is not a loop, so plan your transportation accordingly.',
    bathroom: true,
    familyFriendly: true,
    gpsCoordinates: '45.540874, -122.726184',
    elevationChart: 'assets/elevation-profile/stumptown-half.png'
};

const saltzmanwhirl = {
    id: 'saltzmanwhirl',
    name: 'Saltzman Whirl',
    description: 'Climb the entire Saltzman trail from Highway 30 to Skyline Blvd for spectacular views and burning glutes, then descend Firelane 5 till you meet back up with Saltzman.',
    distance: '6.2',
    elevation: '1016',
    favorite: false,
    completed: false,
    imageMapPage: 'assets/images/lowerpark/leif1.jpg',
    imageOne: 'assets/images/midpark/mid2.jpg',
    imageTwo: 'assets/images/midpark/mid5.jpg',
    imageThree: 'assets/images/midpark/trillium.jpg',
    imageFour: 'assets/images/lowerpark/wildcherry1.jpg',
    thumbnailMap: 'assets/working/saltzman-whirl.svg',
    largeMap: 'assets/working/saltzman-whirl.svg',
    extraInfo: 'This route is open to equestrians, pedestrians, and cyclists. Street parking is available at the trailhead.',
    bathroom: false,
    familyFriendly: false,
    gpsCoordinates: '45.540874, -122.726184',
    elevationChart: 'assets/elevation-profile/stumptown-half.png'
};

const forestParkOptions = [forestParkMarathon, ramblers, half, ultra, springville, saltzman, trilliumtrek, pittock, saltzmanwhirl];

export default forestParkOptions;